# Generated by Django 3.0.4 on 2020-06-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='chat_id')),
                ('city', models.CharField(max_length=250, verbose_name='Город')),
                ('vegetables_fruits_nuts', models.BooleanField(verbose_name='Овощи фрукты, орехи')),
                ('cereals_pasta', models.BooleanField(verbose_name='Крупы, макаронные изделия')),
                ('meat_fish', models.BooleanField(verbose_name='Мясное, рыба')),
                ('juices_water', models.BooleanField(verbose_name='Соки, воды')),
                ('bakery_confectionery_products', models.BooleanField(verbose_name='Хлебобулочные и кондитерские изделия')),
                ('canned_food', models.BooleanField(verbose_name='Консервы')),
                ('alcohol', models.BooleanField(verbose_name='Алкоголь')),
                ('dairy_products', models.BooleanField(verbose_name='Молочная продукция')),
                ('ready_meals', models.BooleanField(verbose_name='Готовые блюда')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-created',),
            },
        ),
    ]
