# Generated by Django 3.0.4 on 2020-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0007_productсategory'),
        ('bot', '0003_auto_20200617_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgusers',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='tgusers',
            name='bakery_confectionery_products',
        ),
        migrations.RemoveField(
            model_name='tgusers',
            name='canned_food',
        ),
        migrations.RemoveField(
            model_name='tgusers',
            name='cereals_pasta',
        ),
        migrations.RemoveField(
            model_name='tgusers',
            name='dairy_products',
        ),
        migrations.RemoveField(
            model_name='tgusers',
            name='juices_water',
        ),
        migrations.RemoveField(
            model_name='tgusers',
            name='meat_fish',
        ),
        migrations.RemoveField(
            model_name='tgusers',
            name='ready_meals',
        ),
        migrations.RemoveField(
            model_name='tgusers',
            name='vegetables_fruits_nuts',
        ),
        migrations.AddField(
            model_name='tgusers',
            name='categories',
            field=models.ManyToManyField(to='vk_parser.ProductСategory', verbose_name='Категория'),
        ),
    ]
