# Generated by Django 3.0.4 on 2020-06-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='VKGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название группы')),
                ('url', models.CharField(max_length=250, unique=True, verbose_name='Ссылка на группу Вк')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vk_parser.Cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'группу',
                'verbose_name_plural': 'Вк группы',
                'ordering': ('-created',),
            },
        ),
    ]
