# Generated by Django 3.0.4 on 2020-06-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'город', 'verbose_name_plural': 'Города'},
        ),
        migrations.RemoveField(
            model_name='vkgroups',
            name='city',
        ),
        migrations.AddField(
            model_name='vkgroups',
            name='city',
            field=models.ManyToManyField(to='vk_parser.Cities', verbose_name='Город'),
        ),
    ]
