# Generated by Django 3.0.4 on 2020-06-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0002_auto_20200617_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkgroups',
            name='url',
        ),
        migrations.AddField(
            model_name='vkgroups',
            name='group_id',
            field=models.CharField(default='', max_length=250, verbose_name='id группы'),
            preserve_default=False,
        ),
    ]
