# Generated by Django 3.0.4 on 2020-06-17 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0003_auto_20200617_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkgroups',
            name='city',
        ),
        migrations.AddField(
            model_name='vkgroups',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='vk_parser.Cities', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
