# Generated by Django 3.0.4 on 2020-06-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0004_auto_20200617_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductСategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
    ]
