# Generated by Django 3.0.4 on 2020-06-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0005_productсategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductСategory',
        ),
    ]
