# Generated by Django 3.0.4 on 2020-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_parser', '0007_productсategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vkgroups',
            name='city',
        ),
        migrations.AddField(
            model_name='vkgroups',
            name='city',
            field=models.ManyToManyField(to='vk_parser.Cities', verbose_name='Город'),
        ),
    ]
